targets:
  $default:
    sources:
      - $package$
      - "lib/**"
      - "node/**"
    builders:
      build_node_compilers|entrypoint:
        options:
          compiler: dart2js
          dart2js_args:
            # TODO: Remove after migrating build_node_compilers to nnbd.
            - --no-sound-null-safety
            - -O4
