name: e2e_interop_test
description: End-to-end test for node interop and builders
version: 0.0.1

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  node_interop:
    path: ../node_interop

dev_dependencies:
  test: ^1.0.0
  build_runner: ^1.0.0
  build_node_compilers:
    path: ../build_node_compilers
