@TestOn('vm')
import 'dart:io';

import 'package:test/test.dart';

void main() {
  group('Hello world', () {
    tearDown(() {
      final buildDir = new Directory('build');
      if (buildDir.existsSync()) {
        buildDir.deleteSync(recursive: true);
      }
    });

    test('compiles with dartdevc', () {
      final compile = Process.runSync(
          'pub', ['run', 'build_runner', 'build', '--output', 'build']);
      expect(compile.exitCode, 0);
      final run = Process.runSync('node', ['build/node/hello_world.dart.js'],
          runInShell: true);
      expect(run.exitCode, 0);
      expect(run.stdout, 'Hello world\n');
    });

    test('compiles with dart2js', () {
      final compile = Process.runSync('pub', [
        'run',
        'build_runner',
        'build',
        '--define',
        'build_node_compilers|entrypoint=compiler=dart2js',
        '--output',
        'build',
      ]);
      expect(compile.exitCode, 0, reason: compile.stdout);
      final mainScript = new File('build/node/hello_world.dart.js');
      expect(mainScript.readAsStringSync(), contains('Generated by dart2js'));

      final run = Process.runSync('node', ['build/node/hello_world.dart.js'],
          runInShell: true);
      expect(run.exitCode, 0);
      expect(run.stdout, 'Hello world\n');
    });
  });
}
